name = input("Insira seu nome ")
age = input("Insira sua idade ")
print(f"Olá {name} como vai? você tem {age} anos de idade e está apto para o mercado de trabalho")
nacionalidade = input("Insira sua nacionalidade ")
print(f"Que bacana {name}, você é {nacionalidade}, muito legal.")